### ISSUE TITLE
rust: fix receiver specs for project 1-3 and code for project 3

### ISSUE THREAD

**Issue by brson** [pingcap/talent-plan#123]
None of the specs say whether to use `&self` or `&mut` - they actually imply that the methods are static, which is totally bogus.

In 1-3 they should be `&mut self`. In project 4 they change to `&self`.

**Comment by sticnarf** [comment]
> In 1-3 they should be &self. In project 4 they change to &mut.

Should be:
In 1-3 they should be &mut self. In project 4 they change to &self.

**Comment by brson** [comment]
Fixed.
