### ISSUE TITLE
kvraft: Need some help on futures unbounded receiver(read from apply_ch)

### ISSUE THREAD

**Issue by printfinn** [pingcap/talent-plan#130]
I hate to ask it, but may I have some hint on how I could **read** the items from this `"unbounded receiver" apply_ch`?

https://github.com/pingcap/talent-plan/blob/d4f84df8fd3eddfbdf5ebf3488d32eb737860e9b/dss/src/kvraft/server.rs#L24

To `send` to `tx` is easy, but reading from this unbounded channel is really painful.

I tried to use `poll` method of Stream:

`match server.apply_ch.poll()`, 

but causes: 
"thread panicked at 'no Task is currently running'".

It seems that if there is already an item in the channel, poll works well, but when the channel is empty, then the thread panics.

I googled and found that the community has had a long term discussion and debate on how `poll` is confusing beginners using futures. 

BTW, future has been involved in std(nightly) this month, but the `poll` in std::future API differs from that in future::futures.

Has anyone done this part and would love to discuss with me? Thanks so much!

**Comment by wjhuang2016** [comment]
Try `for_each()`.  https://github.com/pingcap/talent-plan/blob/d4f84df8fd3eddfbdf5ebf3488d32eb737860e9b/dss/src/raft/config.rs#L379-L413

**Comment by printfinn** [comment]
> Try `for_each()`.
> 

Thanks so much @wjhuang2016  for your kind help!

I did try `for_each`, but wouldn't that consume the `apply_ch`?

```rust
fn for_each<F, U>(self, f: F) -> ForEach<Self, F, U>
```
https://docs.rs/futures/0.1.26/futures/stream/trait.Stream.html#method.for_each
That takes a `self`, I figure this needs to be a `&mut self` or something.

If I write like this:
```rust
let apply = server.apply_ch.for_each(move |cmd: raft::ApplyMsg| {
    println!("{:?}", cmd);
    Ok(())
})
.map_err(move |e| debug!("Read from apply_ch err: {:?}", e));
```

Then it gives me 
```rust 
error: cannot move out of borrowed content
```

Am I wrong for something? Really hope to hear from you more!

**Comment by wjhuang2016** [comment]
@printfinn 
`let (tx, rx) = unbounded();`
The `tx` is `apply_ch` in raft, you should call `for_each()` for `rx`

**Comment by printfinn** [comment]
> `let (tx, rx) = unbounded();`
> The `tx` is `apply_ch` in raft, you should call `for_each()` for `rx`

Thanks @wjhuang2016 ! I noticed this line, in raft it is so, but actually in kvraft, this `rx` turned into `apply_ch` somehow.

But whatever, I figured out another way round reading from `unbounded`, it's ugly but works so far(chaining an `unbounded` and a `std::mpsc::channel` in a weird way).

Anyway, you inspired me a lot, thanks for your help!
