### ISSUE TITLE
KVRaft: RPC Seems Blocking the Whole RPC Network

### ISSUE THREAD

**Issue by printfinn** [pingcap/talent-plan#155]
Hi, I come across the problem when implementing KVRaft 3A.

I could pass `test_basic_3a`, where there is only one client.

But in `test_concurrent_3a`, a weird blocking problem appears, I have simplified the code to make the problem more obvious, here is what I did:

----------------------------------------------------------------------------
Two clients call `put_append RPC` to one same KVServer(leader or follower) at the same time;

KVServer's `put_append handler` does one thing and only one thing: `thread::sleep(5 Seconds)`;

So KVserver is sleeping, but in my opinion, its `Raft Module` should work as normal (i.e. sends heartbeat to maintain its authority). But, after a `Raft Election Timeout` (from the time when the KVServer receives these two RPCs), all other raft module becomes candidate and request votes from others, and as I observed, no one could receive any RPC from anyone.

----------------------------------------------------------------------------

Above is a simplified version, in my real implementation(which passed one client test_basic_3a), this problem still exists, this is how it comes:

Like before, two clients call `put_append RPC` to KVServer(leader) at the same time;

Node is locked, so I can focus on dealing with one RPC at a time.

KVServer's `put_append handler` calls `Raft.start(&message)` once, which would send `AppendEntries RPC` to peers;

If what I'm suspecting is correct: the two client RPC calls is blocking the whole RPC network, thus no `AppendEntries RPC` will be received by peers, such that the KVServer(leader server) `Polls` `apply_ch` but cannot get a response, and waits forever.

Then after a `Raft Election Timeout` this leader loses its leadership.

Loops.

----------------------------------------------------------------------------

I hope someone could help me with this problem, is this a common problem or has anyone got the KVRaft task done without encountering the blocking problem?

Below is part of my simplified code, if someone interested in trying himself.

---
In client.rs

```rust
impl Clerk {
    fn put_append(&self, op: Op) {
        let reply = self.servers[leader_i].put_append(&Op_args)
                         .map_err(Error::Rpc).wait();
    }
}
```

In server.rs
```rust
impl Node {
    pub fn new(kv: KvServer) -> Node {
        Node {
            server: Arc::new(Mutex::new(kv)),
        }
    }
}

impl KvService for Node {
    fn get(&self, arg: GetRequest) -> RpcFuture<GetReply> {
        unimplemented!()
    }

    fn put_append(&self, arg: PutAppendRequest) -> RpcFuture<PutAppendReply> {
        thread::sleep(5000 * MILLIS);
        unimplemented!()
    }
}
```

I think I can work around this problem by letting KVServer refuse the second RPC from Client, such that there could be only one RPC not responsed at one time, but this shouldn't be the correct way right?

**Comment by overvenus** [comment]
Hi @printfinn !

This is a common problem, the root cause is we have limited threads, so please do not execute blocking code in RPC handlers, it will block the whole network. In your example, we can replace `thread::sleep()` with `futures_timer::Delay::new(5s)` then we can execute as many concurrent RPCs as we like.

**Comment by printfinn** [comment]
Hi @overvenus,

Thanks for the quick reply! I tried on your idea, I think I'm closer to success now, but still have some concerns.

With your suggestion, I did pass test_basic_3a on KVRaft (one client test), but when there are two or more clients, I still don't know how to ACTUALLY wait for Raft to reach an agreement without blocking the whole RPC network .

---
As before, I simplified my code again to make it more obvious, 

```rust
fn put_append(&self, arg: PutAppendRequest) -> RpcFuture<PutAppendReply> {
    futures_timer::Delay::new(5000 * MILLIS);
    unimplemented!()
}
```
Code above would not ACTUALLY wait, it seems to have started a new thread to wait.

---
Then there is a version that actually waits but blocks:
```rust
fn put_append(&self, arg: PutAppendRequest) -> RpcFuture<PutAppendReply> {
    futures_timer::Delay::new(5000 * MILLIS)
    .map(|()| println!("printed after 5 seconds"))
     .wait()
     .unwrap();
    unimplemented!()
}
```
This code above would ACTUALLY wait, but blocking the network. ([futures-timer v 0.1.1](https://docs.rs/crate/futures-timer/0.1.1))

What is confusing me is: A KVServer NEEDS to wait for Raft to reach an agreement, then Raft sends that Entry to `apply_ch`, so KVServer can read the receiving end of `apply_ch`. But if I use `futures_timer::Delay::new(5000 * MILLIS)` (the former version), which does not actually wait, to wait for Raft, that's not gonna work, right? Because this `wait` finished immediately, while Raft hasn't reached an agreement. However if I use the latter version, `futures_timer::Delay::new(5 Secs).map(x).wait().unwrap()`, it would block again just like `thread::sleep(5 Secs)`, and no RPC is received by any peer.

Is there something I can do to solve this RPC network blocking problem? Or am I misusing or misunderstanding your idea? Hope to hear from you soon!

**Comment by overvenus** [comment]
Hi @printfinn!

> This code above would ACTUALLY wait, but blocking the network. (futures-timer v 0.1.1)

Yes, because we call `wait()` on the `Delay` future, it essentially converts the delay future to `thread::sleep(5s)`, it blocks. Try this:

```rust
fn put_append(&self, arg: PutAppendRequest) -> RpcFuture<PutAppendReply> {
    let f = futures_timer::Delay::new(5000 * MILLIS)
                 .map(|_| { println!("printed after 5 seconds"); PutAppendReply::new() })
                 .map_err(|_| panic!("should not happen"));
    Box::new(f)
}
```

> But if I use futures_timer::Delay::new(5000 * MILLIS) (the former version), which does not actually wait, to wait for Raft, that's not gonna work, right?

The network is executed asynchronously, in order to **wait** for Raft, we can use `futures::sync::oneshot::channel`, it returns a sender and a receiver. Raft sends responses into the sender, and the receiver receives responses and returns them to the network.

```rust
fn rpc_handler(&self, Req) -> RpcFuture<Resp> {
    let (tx, rx) = channel();
    // After Raft reaches agreement, it then send a response to the tx. 
    // Note: this call must not block the handler. 
    raft.handle(req, tx);
    // It proxies the response from the raft to the network. 
    Box::new(rx)
}

**Comment by printfinn** [comment]
Hi @overvenus !

Works like a charm and really fast!

Thanks sooooooo much!
