### ISSUE TITLE
Organize main.rs differently in Rust projects

### ISSUE THREAD

**Issue by brson** [pingcap/talent-plan#16]
Per discussion in https://github.com/pingcap/talent-plan/pull/10, the way I chose to to put the binary source at `src/bin/main.rs` is awkward because it produces a binary called `main`, which has to be explained. Putting that file somewhere else would do the right thing by default and avoid the subject.

Today I _think_ it would be better to move this somewhere else, probably either `src/bin/kvs.rs` or `src/main.rs`. Need to decide which is the better practice. I'm inclined to go with the former, as putting `lib.rs` and `main.rs` in the same folder is a bit confusing, with the source for both intermingling.

**Comment by sticnarf** [comment]
I agree it's better to just rename `src/bin/main.rs` to `src/bin/kvs.rs`. In case we need to add other executables, it looks better to place all executables in the same directory.

**Comment by brson** [comment]
FIxed.
