### ISSUE TITLE
Rust: Maybe a typo in comments

### ISSUE THREAD

**Issue by Fullstop000** [pingcap/talent-plan#179]
Both in project 4 and project 5: 
https://github.com/pingcap/talent-plan/blob/411c857cc2342bf7813611c1da78caa3d99f4a92/rust/projects/project-5/src/thread_pool/mod.rs#L28

`&mdash` suppose to be a character escape.  Is this a trick to satisfy rust doc validating?

**Comment by brson** [comment]
@Fullstop000 that should actually work! Markdown interprets HTML escapes and Rust doc comments are markdown.

**Comment by Fullstop000** [comment]
Oh, that's right. The origin comments are not WYSIWYG in the code which teaches me a good lesson 😎.
