### ISSUE TITLE
kvraft: generic_test with unreliable and crash args set to true

### ISSUE THREAD

**Issue by NingLin-P** [pingcap/talent-plan#195]
Hi, I am working on the `kvraft` lab, and I find my code pass or not pass some tests randomly,
and I had spent long time to debug with it (use ```println!``` 🙂), it leads me to the tests, and the
Rpc framework, and I not sure is it just bugs of my implement or the tests, but here is what I found:
within the ```generic_test``` function, if the crash arg set to true, the tester will isolating all server's network, so servers can't not reach neither other servers nor the clients, and the tester also take a clone of all server's persister. And there come the problem: the Rpc framework only check network connection and set up network environment(to simulate worse network environment) when request comes in and pull it to the `poller` to simulate network, **but** the Rpc framework will not check network connection when simulate finished and process the reply base on the network environment seted up when request come in. 
And come back to the test, when the tester call ```shutdown_server``` on a server, the situation mentioned on the defination of ```shutdown_server``` may still happen:
```
    // disable client connections to the server.
    // it's important to do this before creating
    // the new Persister in saved[i], to avoid
    // the possibility of the server returning a
    // positive reply to an Append but persisting
    // the result in the superseded Persister.
    self.net.delete_server(&format!("{}", i));
```
specifiy when a client send a `PutAppand` request to the leader, and the leader send the `append_entries` request to majority of the followers, and then tester call ```shutdown_server``` on all server and create new Persister base on the Persister of a server. But as Rpc framework do not check network on reply, the majority of follower can still response to leader, and leader can still response a positive reply to client, and leader and follower persisting the result in the superseded Persister. This happen only when tester call ```shutdown_server``` between 
1. leader send the `append_entries` request to majority of the followers
2. Rpc framework finish simulate of the network transfer and dispatch request to followers for process

usually this interval will be very small but when the ```unreliable``` arg to ```generic_test``` set to true there will be a ```short_delay``` in this interval which increasing the possibility, and also when implementing lease read, all log entries will be ```PutAppend``` command, and also increasing the  possibility, and in my implement of `kvraft` which happend 10s times pass and 1 time not pass mainly on tests: 
```test_persist_concurrent_unreliable_3a``` and ```test_snapshot_unreliable_recover_3b```
like: panicked at  '1 missing element "x 1 31 y" in Append result ...
And that is what I find, I not really sure is it jut a bug of my implement, as I am new to Rust, may be there are just some native misunderstanding of the tests and the Rpc framework, and I very need help on it, thanks advance .

**Comment by siddontang** [comment]
Thanks @NingLin-P 

PTAL @overvenus

**Comment by overvenus** [comment]
Thanks for the report @NingLin-P ! It's a bug of the RPC, could you fix it?

**Comment by NingLin-P** [comment]
I had committed a PR

**Comment by printfinn** [comment]
Hi @NingLin-P !

Thanks for your PR, I'm also encountering similar problems, like 1 out of 10 times I might got 
`thread '<unnamed>' panicked at 'get wrong value, key "2", wanted:
"x 2 0 yx 2 1 yx 2 2 yx 2 3 yx 2 4 yx 2 5 yx 2 6 yx 2 7 yx 2 8 yx 2 9 yx 2 10 yx 2 11 yx 2 12 yx 2 13 yx 2 14 yx 2 15 yx 2 16 yx 2 17 yx 2 18 yx 2 19 yx 2 20 yx 2 21 yx 2 22 yx 2 23 yx 2 24 yx 2 25 yx 2 26 yx 2 27 yx 2 28 yx 2 29 yx 2 30 yx 2 31 yx 2 32 yx 2 33 yx 2 34 yx 2 35 yx 2 36 yx 2 37 yx 2 38 yx 2 39 yx 2 40 yx 2 41 y",
`
`got "x 2 0 yx 2 1 yx 2 2 yx 2 3 yx 2 4 yx 2 5 yx 2 6 yx 2 7 yx 2 8 yx 2 9 yx 2 10 yx 2 11 yx 2 12 yx 2 13 yx 2 14 yx 2 15 yx 2 16 yx 2 17 yx 2 18 yx 2 19 yx 2 20 yx 2 21 yx 2 22 yx 2 24 yx 2 25 yx 2 26 yx 2 27 yx 2 28 yx 2 29 yx 2 30 yx 2 31 yx 2 32 yx 2 33 yx 2 34 yx 2 35 yx 2 36 yx 2 37 yx 2 38 yx 2 39 yx 2 40 yx 2 41 y"'
`
miss 23 there.
This is the last test of kvraft 3b.
Have you stably passed 3b tests? No a single failed test like `panicked at '1 missing element "x 1 31 y" in Append result ...`?

I'm also new to Rust, looking forward to hear from you!
