### ISSUE TITLE
Set up a tool to test for simple language

### ISSUE THREAD

**Issue by brson** [pingcap/talent-plan#21]
This project is intended in part for a Chinese audience who may not have strong English skills. There are tool to help enforce the use of simplified language (look into hemmingway). Set up a test harness that scans all the text in the Rust course and verifies that the language used is acceptably simple.

**Comment by sticnarf** [comment]
I've tried the Hemingway editor on the current text of the first three projects. It only tells me there are some complex words or phrases. Then I look into them and I believe those words or phrases shouldn't be a problem for a Chinese audience.

**Comment by brson** [comment]
Thanks for looking into it @sticnarf

**Comment by brson** [comment]
I'm just going to close this.
