### ISSUE TITLE
project-2 issue

### ISSUE THREAD

**Issue by Matrix-Zhang** [pingcap/talent-plan#224]
the code at https://github.com/pingcap/talent-plan/blob/master/rust/projects/project-2/src/kv.rs#L70
```
let current_gen = gen_list.last().unwrap_or(&0) + 1;
```
if first command is get, it should be always have a empty log file for first one,

change to
```
        let current_gen = gen_list.last().map(|v| *v).unwrap_or_else(|| 1);
```
better ?

**Comment by sticnarf** [comment]
It depends on your design. The code just ensures that a new log file is created every time we open a `KvStore`.
Of course, it is quite strange before we have a DB server (I believe you've found `kvs get` command creates a new log).

**Comment by Matrix-Zhang** [comment]
kvs get create a new log is normal, 
for example:
kvs get 1 one, will create 1.log
kvs set 1 one, will create 2.log, the 1.log is empty, my viewpoint is this...

**Comment by Hoverbear** [comment]
I think this is resolved so closing this. :)
