### ISSUE TITLE
Remove lessons from plan and remove questions from project 1

### ISSUE THREAD

**Issue by brson** [pingcap/talent-plan#25]
For the MVP, I am only planning on implementing the projects and gathering the required background reading material to implement them. So any lessons will not be written for quite a while. Their presence in the plan is distracting to reviewers.

The questions in project 1 have not worked out.

So let's remove both. Delete the lessons from plan.md, putting their topics back in notes.md under the section listing potential topics. Delete the questions from project 1 and the corresponding answers.

@sticnarf will you do this?

**Comment by sticnarf** [comment]
Created #29 for this. PTAL.
