### ISSUE TITLE
`p` is always been `{10000 [0.3 0.3 0.3]}`

### ISSUE THREAD

**Issue by yashiro1899** [pingcap/talent-plan#254]
https://github.com/pingcap/talent-plan/blob/1feb39fc7ce7bb8c7a7eeaed32cf3b2944b3350a/tidb/mapreduce/casegen.go#L120

**Comment by yashiro1899** [comment]
`p` is always been `{10000 [0.3 0.3 0.3]}`

**Comment by lamxTyler** [comment]
PTAL @qw4990
