### ISSUE TITLE
Broken TiKV deep dive link

### ISSUE THREAD

**Issue by Novemser** [pingcap/talent-plan#262]
The original link https://tikv.org/deep-dive/ in the current master branch (https://github.com/pingcap/talent-plan/blob/b608afb4b5513442abcf79df45ba346d721b9908/rust/README.md#a-pingcap-specific-note) does not exist anymore, shall we replace with a correct one?

**Comment by tagesholly1** [comment]
The original link https://tikv.org/deep-dive/ in the current master branch (https://github.com/pingcap/talent-plan/blob/b608afb4b5513442abcf79df45ba346d721b9908/rust/README.md#a-pingcap-specific-note) does not exist anymore, shall we replace with a correct one?
