### ISSUE TITLE
udpate the `README.md` according to the RFC

### ISSUE THREAD

**Issue by zz-jason** [pingcap/talent-plan#330]
### Is your feature request related to a problem?

Not a problem.

### Describe the feature you'd like

Since we are now developing the courses for Talent Plan 2.0. `README.md` needs to be updated to introduce the new Talent Plan.

### Describe alternatives you've considered

No.

**Comment by Soline324** [comment]
Done in https://github.com/pingcap/talent-plan/pull/338
