### ISSUE TITLE
duplicate "part3" in Rust section-1

### ISSUE THREAD

**Issue by mapleFU** [pingcap/talent-plan#56]
In Rust section-1 <Project: Tools and good bones>, duplicate "part-3" occurs in the document:

* [Cargo environment variables](https://github.com/pingcap/talent-plan/blob/master/rust/projects/tools/project.md#part-3-cargo-environment-variables)
* [Store values in memory](https://github.com/pingcap/talent-plan/blob/master/rust/projects/tools/project.md#part-3-store-values-in-memory)

I wonder if there is something wrong here.

**Comment by sticnarf** [comment]
@mapleFU

Yes. It's a mistake. 

 More issues are welcome if you find anything else strange or run into any problem. Thanks a lot!
