### ISSUE TITLE
Use multiple logs in Rust training course code

### ISSUE THREAD

**Issue by sticnarf** [pingcap/talent-plan#71]
In the text of project 2, we intended to simplify the bitcask algorithm using only one log file. After some practice, it is found that a single log file makes implementation more complex instead of simplifying it.

So I think we should not ask students to use only one log, and then give instructions of using multiple logs or at least give some hints.

**Comment by brson** [comment]
Agreed. This is going to complicate the explanation quite a bit as the reasons for using multiple logs are multiple and subtle.

**Comment by brson** [comment]
@sticnarf I split this issue into separate ones for code and text and assigned this one to you. You can go ahead and make the code changes, and write up how your solution works in the PR, and I will follow your lead with the text.

cc @mapleFU this will change the solutions quite a bit
